### PR TITLE
Fix #153 (screen freezing issues)

### LINKED ISSUE #153: wlr_output_commit sometimes start to fail a lot
Tested on [current master](cbd4a2807bcfa74cc87c36d7ec20cdf92a7c77fc) the rendering "freezes".

My setup consists of two outputs. One 1080p laptop display and an external 4k output connected via displayport.

I did the following:
1. Open river
2. Spawn a bunch of terminals (foot)
3. Change the layout a couple of times to cause calls to `root.startTransaction`
4. Now changing the layout did not result in a visual change
5. Change focus to my other output and spawn a terminal. I didn't see any visual change here either
6. Change VT back and fourth
7. Now the rendering works as expected

I can kind of reliably reproduce this. The steps above lead to this most of the time.

Here are the logs: https://paste.sr.ht/~maringuu/bb42efa93eeed27b3d8d53258c907ee9f2771f87

Here are some other logs where the rendering also froze: 
https://paste.sr.ht/~maringuu/862ccc42f315baeeadffcd20fe667ad604027689

Edit:
I figured out a simpler way to reproduce. It works very reliable for me.
1. Open river
2. Open at least two terminals (foot)
3. Do `riverctl swap next` a bunch of times until it freezes

### PR DESCRIPTION
**Pull request by Q-I-U**
This should fix rendering "freezes" reported in #153
Tested on FreeBSD 14-current

### CODE REVIEW

File: river/render.zig [hunk 1]
```diff
@@ -143,8 +143,12 @@ pub fn renderOutput(output: *Output) void {
     }
 
     // TODO: handle failure
-    output.wlr_output.commit() catch
+    if (output.wlr_output.commit()) |_| {
+        return;
+    } else |_| {
+        renderOutput(output);
         log.err("output commit failed for {}", .{output.wlr_output.name});
+    }
```
Comment (ifreund) [inline river/render.zig:151]:
```suggestion
    output.wlr_output.commit() catch {
        log.err("output commit failed for {}, retrying", .{output.wlr_output.name});
        renderOutput(output);
    };
```

**Review by ifreund — COMMENTED** [review]
Won't this cause river to enter an infinite loop if committing the output always fails?

Why does this work in the first place, did you figure you figure out the cause of #153?

**Comment by Q-I-U** [comment]
I also thought that setting a maximum amount of retries would be a good idea, but the number of needed retries is pretty random ranging form a few retries to sometimes over 100.
When I was using river like this for a few hours it didn't get stuck in a loop, so I guess that It always
renders the output, sometimes it just takes a few tries.

For me the freezes only occurred when the screen was getting redrawn very fast ie. when playing a game

**Comment by Leon-Plickat** [comment]
So... why would this work? If `renderOutput()` fails, river would try again on the next `output.frame` event anyway.

**Comment by Q-I-U** [comment]
I see, I will investigate this further in that case. I will update the pull request if I find a better approach.
For me to "un-stuck" river (without this patch) I had to switch to a tty and then back to river. 
So I guess that for some reason `output.frame` is only triggered only when switching ttys after `renderOutput()` fails

**Comment by Q-I-U** [comment]
Ok, so it looks like when `wlr_output.commit()` fails it runs `output_state_clear()` which
prevents the frame event from being triggered later on. I changed the patch so it uses `scheduleFrame` 
which AFAIK directly emits the `events.frame` event. This should solve the infinite loop problem the 
previous version had.

I think this is the most direct way to solve the problem.

File: river/render.zig [hunk 2]
```diff
@@ -143,8 +143,10 @@ pub fn renderOutput(output: *Output) void {
     }
 
     // TODO: handle failure
```
Comment (ifreund) [inline river/render.zig:145]:
```suggestion
```

File: river/render.zig [hunk 3]
```diff
@@ -143,8 +143,10 @@ pub fn renderOutput(output: *Output) void {
...
-    output.wlr_output.commit() catch
-        log.err("output commit failed for {}", .{output.wlr_output.name});
+    output.wlr_output.commit() catch {
+        log.err("output commit failed for {}, retrying", .{output.wlr_output.name});
```
Comment (ifreund) [inline river/render.zig:147]: Lets fix this to stop at the null terminator instead of printing the full array since we're already touching this line.
```suggestion
        log.err("output commit failed for {}, retrying", .{std.mem.spanZ(&output.wlr_output.name)});
```

**Review by ifreund — COMMENTED** [review]
Scheduling a new frame looks like it does what what we want here, good find.

**Review by ifreund — APPROVED** [review]
LGTM, Thanks!
