### PR TITLE
Cursor: fix move/resize with high poll rate/low dpi mice

### LINKED ISSUE #255: Moving/Resizing views with high polling rate mouse doesn't work properly
I recently got a new mouse and the first thing I noticed is that moving views around the screen felt weird, kinda like it didn't want to move sometimes.

I believe this is because River converts delta_x and delta_y into ints to move the view and then moves the cursor based on the difference in the current and pending positions of the view.

This can also be replicated by moving your mouse really slowly.

### PR DESCRIPTION
**Pull request by ifreund**
Fixes #255

### CODE REVIEW

File: river/Cursor.zig [hunk 1]
```diff
@@ -768,22 +780,33 @@ fn processMotion(self: *Self, device: *wlr.InputDevice, time: u32, delta_x: f64,
                 self.wlr_cursor.y - @intToFloat(f64, output_box.y + view.current.box.y - view.surface_box.y),
             );
         },
-        .move => |view| {
-            view.move(@floatToInt(i32, delta_x), @floatToInt(i32, delta_y));
+        .move => |*data| {
+            dx += data.delta_x;
+            dy += data.delta_y;
+            data.delta_x = dx - @round(dx);
+            data.delta_y = dy - @round(dy);
```
Comment (Bonicgamer) [inline river/Cursor.zig:787]: We need to use trunc here instead since round can round up.
For instance with using round, if our "new" dx value were 0.9, it would round to 1.0 which would mean data's delta_x is going to be -0.1. If dx was 0.9 again, our "new" dx value would be 0.8 when it should be 1.8 (0.9 + 0.9 = 1.8 just in case my explanation wasn't clear).

```suggestion
            data.delta_x = dx - @trunc(dx);
            data.delta_y = dy - @trunc(dy);
```

**Review by Bonicgamer — CHANGES_REQUESTED** [review]
Thanks for trying to fix this issue I was having! Most of it seems to work, but there was a slight thing that needs to be fix which I explained in the one of the comments/suggestions.
With the small tweak, it works perfectly for me!
This is my first time using the Github code review thing so I hope it works nice.

File: river/Cursor.zig (hunk 1 above)
Comment (ifreund) [reply river/Cursor.zig:787]: Great catch, the semantics of `@trunc()` are indeed what I intended here!
